const SUPABASE_URL='https://dnkflankolstrjqhpzrs.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_Vqy8k9JkpAL6o5EX2pV6ww_6uFb3Fcm';

const DEFAULT_CATEGORIES=['3. Säule','Ausgang','Auto','Bücher','Einnahmen','Essen','Ferien','Festivals','Gesundheit','Kleider','Lohn','Motorrad','ÖV','Pflege','Ramon','Salt','Steuern','Twint','Undefinierbar','Darlehen an 3te'];
const DEFAULT_ACCOUNTS=['Kasse','BEKB','BBO','Kreditkarte'];
const CHF=new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF'});
const isConfigured=!SUPABASE_URL.includes('DEIN-PROJEKT')&&!SUPABASE_ANON_KEY.includes('DEIN-');
const supabase=isConfigured?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
let state={bookings:[],categories:DEFAULT_CATEGORIES,accounts:DEFAULT_ACCOUNTS};
let session=null;
let deferredPrompt=null;

function id(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(16).slice(2)}
function today(){return new Date().toISOString().slice(0,10)}
function signedAmount(b){const n=Number(b.amount)||0;return b.type==='Ausgabe'?-n:b.type==='Einnahme'?n:0}
function monthOf(d){return (d||'').slice(0,7)}
function toDbBooking(b){return{id:b.id,date:b.date,type:b.type,amount:b.amount,category:b.category,account:b.account,target_account:b.targetAccount||null,description:b.description||null,receipt_data:b.receipt||null,updated_at:new Date().toISOString()}}
function fromDbBooking(b){return{id:b.id,date:b.date,type:b.type,amount:Number(b.amount),category:b.category,account:b.account,targetAccount:b.target_account||'',description:b.description||'',receipt:b.receipt_data||'',updatedAt:b.updated_at}}
function fillSelect(el,items,{all=false,blank=false}={}){el.innerHTML='';if(blank)el.add(new Option('',''));if(all)el.add(new Option('Alle','Alle'));items.forEach(v=>el.add(new Option(v,v)));}
function syncSelects(){fillSelect(category,state.categories);fillSelect(account,state.accounts);fillSelect(targetAccount,state.accounts,{blank:true});fillSelect(filterCategory,state.categories,{all:true});fillSelect(filterAccount,state.accounts,{all:true});fillSelect(statsMonth,['Alle','01','02','03','04','05','06','07','08','09','10','11','12']);}
function setDefaults(){date.value=today();statsYear.value=new Date().getFullYear();filterMonth.value='';statsMonth.value='Alle';}
function currentFilters(){return{month:filterMonth.value,category:filterCategory.value||'Alle',account:filterAccount.value||'Alle',text:(filterText.value||'').toLowerCase().trim()};}
function filteredBookings(){const f=currentFilters();return state.bookings.filter(b=>(!f.month||monthOf(b.date)===f.month)&&(f.category==='Alle'||b.category===f.category)&&(f.account==='Alle'||b.account===f.account)&&(!f.text||(b.description||'').toLowerCase().includes(f.text))).sort((a,b)=>(b.date||'').localeCompare(a.date||''));}
function renderEntries(){entryList.innerHTML='';const data=filteredBookings();entryCount.textContent=`${data.length} Buchungen`;const tpl=document.getElementById('entryTemplate');data.forEach(b=>{const node=tpl.content.cloneNode(true);node.querySelector('.entry-title').textContent=b.category;node.querySelector('.entry-meta').textContent=`${b.date} · ${b.type} · ${b.account}${b.targetAccount?' → '+b.targetAccount:''}`;node.querySelector('.entry-desc').textContent=b.description||'';const amt=node.querySelector('.entry-amount');amt.textContent=CHF.format(signedAmount(b));amt.classList.toggle('good',signedAmount(b)>0);amt.classList.toggle('bad',signedAmount(b)<0);node.querySelector('.edit').onclick=()=>editBooking(b.id);node.querySelector('.delete').onclick=()=>deleteBooking(b.id);entryList.appendChild(node);});}
function renderStats(){const year=String(statsYear.value||new Date().getFullYear());const m=statsMonth.value;const data=state.bookings.filter(b=>(b.date||'').startsWith(year)&&(m==='Alle'||(b.date||'').slice(5,7)===m));const income=data.filter(b=>b.type==='Einnahme').reduce((s,b)=>s+Number(b.amount||0),0);const expense=data.filter(b=>b.type==='Ausgabe').reduce((s,b)=>s+Number(b.amount||0),0);kpiIncome.textContent=CHF.format(income);kpiExpense.textContent=CHF.format(expense);kpiResult.textContent=CHF.format(income-expense);renderGrouped(categoryStats,groupBy(data,'category',b=>Math.abs(signedAmount(b))));renderAccounts();}
function groupBy(data,keyFnName,valueFn){const map={};data.forEach(b=>{const k=b[keyFnName]||'Ohne';map[k]=(map[k]||0)+valueFn(b);});return Object.entries(map).sort((a,b)=>b[1]-a[1]);}
function renderGrouped(el,rows){el.innerHTML='';const max=Math.max(1,...rows.map(r=>r[1]));if(!rows.length){el.innerHTML='<p class="muted">Keine Daten.</p>';return;}rows.forEach(([name,val])=>{const div=document.createElement('div');div.className='stat-row';div.innerHTML=`<div><strong>${escapeHtml(name)}</strong><div class="bar"><span style="width:${Math.round(val/max*100)}%"></span></div></div><strong>${CHF.format(val)}</strong>`;el.appendChild(div);});}
function renderAccounts(){const map=Object.fromEntries(state.accounts.map(a=>[a,0]));state.bookings.forEach(b=>{if(!Object.prototype.hasOwnProperty.call(map,b.account))map[b.account]=0;if(b.type==='Einnahme')map[b.account]+=Number(b.amount||0);if(b.type==='Ausgabe')map[b.account]-=Number(b.amount||0);if(b.type==='Transfer'&&b.targetAccount){map[b.account]-=Number(b.amount||0);map[b.targetAccount]=(map[b.targetAccount]||0)+Number(b.amount||0);}});accountStats.innerHTML='';Object.entries(map).forEach(([name,val])=>{const div=document.createElement('div');div.className='stat-row';div.innerHTML=`<strong>${escapeHtml(name)}</strong><strong>${CHF.format(val)}</strong>`;accountStats.appendChild(div);});}
function renderSettings(){categoryChips.innerHTML='';state.categories.forEach(c=>categoryChips.appendChild(chip(c,()=>removeItem('categories',c))));accountChips.innerHTML='';state.accounts.forEach(a=>accountChips.appendChild(chip(a,()=>removeItem('accounts',a))));}
function chip(text,onRemove){const span=document.createElement('span');span.className='chip';span.innerHTML=`${escapeHtml(text)} <button title="Entfernen">×</button>`;span.querySelector('button').onclick=onRemove;return span;}
async function saveSettings(){if(!session)return;const { error }=await supabase.from('app_settings').upsert({user_id:session.user.id,categories:state.categories,accounts:state.accounts,updated_at:new Date().toISOString()});if(error)alert('Listen konnten nicht gespeichert werden: '+error.message);}
async function removeItem(list,value){state[list]=state[list].filter(v=>v!==value);await saveSettings();syncSelects();renderAll();}
async function addItem(list,input){const v=input.value.trim();if(!v||state[list].includes(v))return;state[list].push(v);state[list].sort((a,b)=>a.localeCompare(b,'de-CH'));input.value='';await saveSettings();syncSelects();renderAll();}
async function fileToDataUrl(file){if(!file)return'';if(file.size>1200000){alert('Beleg ist zu gross. Bitte kleiner als ca. 1.2 MB.');return'';}return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});}
async function loadCloudData(){const settingsRes=await supabase.from('app_settings').select('*').maybeSingle();if(settingsRes.error)throw settingsRes.error;if(settingsRes.data){state.categories=settingsRes.data.categories?.length?settingsRes.data.categories:DEFAULT_CATEGORIES;state.accounts=settingsRes.data.accounts?.length?settingsRes.data.accounts:DEFAULT_ACCOUNTS;}else{await saveSettings();}
const bookingsRes=await supabase.from('bookings').select('*').order('date',{ascending:false});if(bookingsRes.error)throw bookingsRes.error;state.bookings=(bookingsRes.data||[]).map(fromDbBooking);syncSelects();setDefaults();renderAll();}
async function boot(){if(!isConfigured){setupWarning.classList.remove('hidden');return;}const {data}=await supabase.auth.getSession();session=data.session;updateAuthUi();if(session)await loadCloudData();supabase.auth.onAuthStateChange(async(_event,newSession)=>{session=newSession;updateAuthUi();if(session)await loadCloudData();});}
function updateAuthUi(){const signed=!!session;authBox.classList.toggle('hidden',signed);appShell.classList.toggle('hidden',!signed);logoutBtn.classList.toggle('hidden',!signed);userStatus.textContent=signed?session.user.email:'Nicht angemeldet';}
loginForm.onsubmit=async e=>{e.preventDefault();authMessage.textContent='';if(!isConfigured){authMessage.textContent='Supabase ist noch nicht konfiguriert.';return;}const email=loginEmail.value.trim();const password=loginPassword.value;const {error}=await supabase.auth.signInWithPassword({email,password});authMessage.textContent=error?'Login fehlgeschlagen: '+error.message:'';};
signupBtn.onclick=async()=>{authMessage.textContent='';if(!isConfigured){authMessage.textContent='Supabase ist noch nicht konfiguriert.';return;}const email=loginEmail.value.trim();const password=loginPassword.value;if(!email||password.length<6){authMessage.textContent='E-Mail und Passwort mit mindestens 6 Zeichen eingeben.';return;}const {error}=await supabase.auth.signUp({email,password});authMessage.textContent=error?'Konto konnte nicht erstellt werden: '+error.message:'Konto erstellt. Falls Supabase E-Mail-Bestätigung verlangt, zuerst den Link im Mail öffnen.';};
logoutBtn.onclick=async()=>{await supabase.auth.signOut();state={bookings:[],categories:DEFAULT_CATEGORIES,accounts:DEFAULT_ACCOUNTS};renderAll();};
bookingForm.onsubmit=async e=>{e.preventDefault();const booking={id:editId.value||id(),date:date.value,type:type.value,amount:Number(amount.value),category:category.value,account:account.value,targetAccount:targetAccount.value,description:description.value.trim(),receipt:await fileToDataUrl(receipt.files[0]),updatedAt:new Date().toISOString()};const old=state.bookings.find(b=>b.id===booking.id);if(old&&!booking.receipt)booking.receipt=old.receipt||'';const {error}=await supabase.from('bookings').upsert(toDbBooking(booking));if(error){alert('Speichern fehlgeschlagen: '+error.message);return;}const idx=state.bookings.findIndex(b=>b.id===booking.id);if(idx>=0)state.bookings[idx]=booking;else state.bookings.push(booking);bookingForm.reset();editId.value='';date.value=today();renderAll();showView('entries');};
resetForm.onclick=()=>{bookingForm.reset();editId.value='';date.value=today();};
function editBooking(idv){const b=state.bookings.find(x=>x.id===idv);if(!b)return;showView('capture');editId.value=b.id;date.value=b.date;type.value=b.type;amount.value=b.amount;category.value=b.category;account.value=b.account;targetAccount.value=b.targetAccount||'';description.value=b.description||'';}
async function deleteBooking(idv){if(!confirm('Buchung löschen?'))return;const {error}=await supabase.from('bookings').delete().eq('id',idv);if(error){alert('Löschen fehlgeschlagen: '+error.message);return;}state.bookings=state.bookings.filter(b=>b.id!==idv);renderAll();}
function renderAll(){renderEntries();renderStats();renderSettings();}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===name));if(name==='stats')renderStats();if(name==='entries')renderEntries();}
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>showView(t.dataset.view));[filterMonth,filterCategory,filterAccount,filterText].forEach(el=>el.oninput=renderEntries);[statsYear,statsMonth].forEach(el=>el.oninput=renderStats);addCategory.onclick=()=>addItem('categories',newCategory);addAccount.onclick=()=>addItem('accounts',newAccount);clearAll.onclick=async()=>{if(confirm('Wirklich alle Cloud-Buchungen löschen?')){const {error}=await supabase.from('bookings').delete().neq('id','00000000-0000-0000-0000-000000000000');if(error){alert('Löschen fehlgeschlagen: '+error.message);return;}state.bookings=[];renderAll();}};
exportJson.onclick=()=>download('buchhaltung-backup.json',JSON.stringify(state,null,2),'application/json');
importJson.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async()=>{try{const data=JSON.parse(r.result);if(!Array.isArray(data.bookings))throw Error();state={bookings:data.bookings,categories:data.categories||DEFAULT_CATEGORIES,accounts:data.accounts||DEFAULT_ACCOUNTS};await saveSettings();const rows=state.bookings.map(b=>toDbBooking({...b,id:b.id||id()}));if(rows.length){const {error}=await supabase.from('bookings').upsert(rows);if(error)throw error;}await loadCloudData();alert('Import abgeschlossen.');}catch(err){alert('Import fehlgeschlagen: '+(err.message||''));}};r.readAsText(f);};
exportCsv.onclick=()=>{const rows=[['Datum','Typ','Betrag','Kategorie','Konto','Zielkonto','Beschreibung'],...filteredBookings().map(b=>[b.date,b.type,b.amount,b.category,b.account,b.targetAccount||'',b.description||''])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n');download('buchungen.csv',csv,'text/csv;charset=utf-8');};
function download(name,content,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden');});installBtn.onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();deferredPrompt=null;installBtn.classList.add('hidden');};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
syncSelects();setDefaults();renderAll();boot().catch(err=>{authMessage.textContent='Fehler beim Laden: '+err.message;});
